apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: nginx-demo
  labels:
    app.kubernetes.io/part-of: nginx-demo
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
