apiVersion: v2
name: loki-stack
description: Umbrella chart for Loki via ArgoCD
type: application
version: 1.0.0
appVersion: "2.9.0"
dependencies:
  - name: loki
    version: "5.41.4"
    repository: "https://grafana.github.io/helm-charts"
